-- 2. Eliminar la tabla original
DROP TABLE Bitacora_Originacion;

-- 3. Recrear la tabla con Registro como IDENTITY
CREATE TABLE Bitacora_Originacion (
    Registro INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    FECHA DATETIME NULL,
    TICKET NVARCHAR(50) NULL,
    SUC INT NULL,
    CLIENTE NVARCHAR(50) NULL,
    VENTA NVARCHAR(50) NULL,
    MOTO NVARCHAR(10) NULL,
    TIPO_DE_CLIENTE NVARCHAR(50) NULL,
    NOTAS NVARCHAR(255) NULL,
    LC_ACTUAL DECIMAL(18,2) NULL,
    LC_FINAL DECIMAL(18,2) NULL,
	LC_DISPONIBLE DECIMAL(18,4) NULL,
    ENGANCHE_REQUERIDO DECIMAL(18,2) NULL,
    ENGANCHE_RECIBIDO DECIMAL(18,2) NULL,
    OBSERVACION NVARCHAR(MAX) NULL,
    ESPECIAL NVARCHAR(100) NULL,
    ARTICULO NVARCHAR(255) NULL,
    EJECUTIVO NVARCHAR(100) NULL,
    CEL_CTE NVARCHAR(20) NULL,
    CONSULTA_BURO NVARCHAR(10) NULL,
    Actualizacion NVARCHAR(10) NULL,
    FACTURO NVARCHAR(20) NULL,
    innecesario NVARCHAR(10) NULL
);

SELECT * FROM LC_Disponible